apiVersion: apps/v1
kind: Deployment
metadata:
  name: freeswitch-focal-ubuntu-packages-runner
  labels:
    app: freeswitch-focal-ubuntu-packages-runner
spec:
  replicas: 2
  selector:
    matchLabels:
      app: freeswitch-focal-ubuntu-packages-runner
  template:
    metadata:
      labels:
        app: freeswitch-focal-ubuntu-packages-runner
    spec:
      containers:
      - name:  freeswitch-focal-ubuntu-packages-runner
        image: docker.pkg.github.com/dniasoff/freeswitch-focal-build-container/freeswitch-focal-build-container:latest
        env:
        - name: GITHUB_OWNER
          value: dniasoff
        - name: GITHUB_REPOSITORY
          value: freeswitch-focal-ubuntu-packages
        - name: RUNNER_TOKEN # stored separately in a Kubernetes secret
          valueFrom:
            secretKeyRef:
              name: GITHUB-PERSONAL-ACCESS-TOKEN
              key: PAT
